name: google_tasks_cli
description: A sample command-line application.
version: 1.0.4
homepage: https://github.com/jakubpradzynski/google_tasks_cli

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1
  http: 0.12.0+4
  prompts: ^1.3.1
  console: ^3.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
